name: Test project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: create release
        run: bash .release.sh
